[package]
name = "aoc16"
version = "0.1.0"
authors = ["TheHugo <the.hugo.lom@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
md5 = "0.7.0"
itertools = "0.7.8"